module.exports={
    configureWebpack:{
        resolve:{
            alias:{
                'assets':'@/assets',
                'components':'@/components',
                'network':'@/network',
                'pages':'@/pages',
                'css':'@/css'
            }
        }
    }
}